payloads:
  db:
    runtime: "vm"
    params:
      image_hash: "283d7bebe2dd26dfc20fcb2e7cc44870f3d18dee830b4e39fa391181"
  backend:
    runtime: "vm"
    params:
      image_hash: "d7556b193580e6ad3867a7cfca9ab07e796c00e5bb723658ce0f12aa"
  frontend:
    runtime: "vm"
    params:
      image_hash: "e742ab3b72d86232282e5ac7a427ba1e35c84e3f2b2231d80c617ca4"
nodes:
  db:
    payload: "db"
    entrypoint:
      # - ["/usr/bin/mkdir", "/var/lib/postgresql/data"]
      # - ["/usr/bin/whoami"]
      # - ["/bin/bash", "-c", "ln -s usr/local/bin/docker-entrypoint.sh"]
      # - ["/bin/mkdir", "-p", "/var/lib/pg_data"]
      # - ["/bin/chmod", "777", "/var/lib/pg_data"]
      # - ["/bin/chown", "postgres:postgres", "/var/lib/pg_data"]
      - ["/bin/chmod", "777", "/"]
      # - ["/docker-entrypoint.sh", "postgres"]
      # - [
      #     "/bin/bash",
      #     "-c",
      #     "su postgres -c '/usr/local/bin/docker-entrypoint.sh postgres'",
      #   ]
      - [
          "/bin/bash",
          "-c",
          "echo listen_addresses = \\'*\\' >> /etc/postgresql/14/main/postgresql.conf",
        ]
      - [
          "/bin/bash",
          "-c",
          "echo 'host  all  all 0.0.0.0/0 md5' >> /etc/postgresql/14/main/pg_hba.conf",
        ]
      - ["/bin/bash", "-c", "/etc/init.d/postgresql start"]
      - [
          "/bin/bash",
          "-c",
          'sudo -u postgres psql -c "ALTER USER postgres PASSWORD ''mysecretpassword''; " ',
        ]
      - [
          "/bin/bash",
          "-c",
          'sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE postgres TO postgres;" ',
        ]

    network: "default"
    ip:
      - "192.168.0.2"
    # http_proxy:
    #   ports:
    #     - "5432" # specify just the remote port, allow the local port to be automatically chosen
  backend:
    payload: "backend"
    entrypoint:
      - ["/bin/bash", "-c", "./react-rust-postgres > log.txt 2>&1 &"]
      - ["/bin/chmod", "777", "/"]
      # - ["/bin/bash", "-c", "sleep 60 && cat log.txt"]
    network: "default"
    ip:
      - "192.168.0.3"
    depends_on:
      - "db"
  frontend:
    payload: "frontend"
    entrypoint:
      - ["/bin/chmod", "777", "/"]
      - ["/docker-entrypoint.sh", "nginx"]
    http_proxy:
      ports:
        - "3000" # specify just the remote port, allow the local port to be automatically chosen
    network: "default"
    ip:
      - "192.168.0.4"
networks:
  default:
    ip: "192.168.0.0/24"
