payloads:
  db:
    runtime: "vm"
    params:
      image_hash: "45d6089fbc0b8b424941863df689fa8fdccce0344e9efa18d3d1315e"
  backend:
    runtime: "vm"
    params:
      image_hash: "d7556b193580e6ad3867a7cfca9ab07e796c00e5bb723658ce0f12aa"
  frontend:
    runtime: "vm"
    params:
      image_hash: "d436707b50f945e3a9c180e9f0407af5b8b84ae606a1e77c1ef37410"
nodes:
  db:
    payload: "db"
    entrypoint:
      - ["/bin/chmod", "777", "/"]
      - ["/bin/bash", "-c", "/etc/init.d/postgresql start"]
      - [
          "/bin/bash",
          "-c",
          'sudo -u postgres psql -c "ALTER USER postgres PASSWORD ''mysecretpassword''; " ',
        ]
      - [
          "/bin/bash",
          "-c",
          'sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE postgres TO postgres;" ',
        ]
    network: "default"
    ip:
      - "192.168.0.2"
  backend:
    payload: "backend"
    entrypoint:
      - ["/bin/bash", "-c", "./react-rust-postgres &"]
    network: "default"
    ip:
      - "192.168.0.3"
    depends_on:
      - "db"
  frontend:
    payload: "frontend"
    entrypoint:
      - ["/bin/chmod", "777", "/"]
      - ["/docker-entrypoint.sh", "nginx"]
    http_proxy:
      ports:
        - "3000" # specify just the remote port, allow the local port to be automatically chosen
    network: "default"
    ip:
      - "192.168.0.4"
networks:
  default:
    ip: "192.168.0.0/24"
